rails -v
Traceback (most recent call last):
	22: from /Users/journ/.rbenv/versions/2.7.7/bin/rails:23:in `<main>'
	21: from /Users/journ/.rbenv/versions/2.7.7/bin/rails:23:in `load'
	20: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/exe/rails:10:in `<top (required)>'
	19: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	18: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	17: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/cli.rb:12:in `<top (required)>'
	16: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	15: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	14: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:3:in `<top (required)>'
	13: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	12: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	11: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support.rb:29:in `<top (required)>'
	10: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 8: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/logger.rb:3:in `<top (required)>'
	 7: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/logger_silence.rb:5:in `<top (required)>'
	 4: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/logger_thread_safe_level.rb:8:in `<top (required)>'
	 1: from /Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/logger_thread_safe_level.rb:9:in `<module:ActiveSupport>'
/Users/journ/.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)
